version: '3'
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo-alpine
    ports:
      - '27017:27017'
  nginx:
    container_name: nginx
    image: nginx-alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - '80:80'
    depends_on:
      - app
      - mongo
  certbot:
    image: certbot/certbot
    - ./data/certbot/conf:/etc/letsencrypt
    - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"